os: linux

language: cpp

script:
  - cmake .
  - make

compiler: gcc

branches:
  only: master

addons:
  apt:
    packages:
    - build-essential
    - flex
    - bison
    - libtool
    - autoconf
    - libncurses5-dev
    - libprotobuf-dev
    - protobuf-compiler

sudo: required

before_install:
  - ./travis/install-build-deps.sh