os: linux

language: cpp

script: ./travis/run-build.sh

compiler: gcc

branches:
  only: master

addons:
  apt:
    packages:
    - build-essential
    - flex
    - bison
    - libtool
    - autoconf
    - libncurses5-dev
    - libprotobuf-dev
    - protobuf-compiler

sudo: required
